development:
  encoding: unicode
  adapter: postgresql
  host: localhost
  database: ivfreports_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ivfreports_test
  pool: 5